### ISSUE TITLE
Incompatible with Gnome Shell 43

### ISSUE THREAD

**Issue by cxt666** [jaystrictor/gnome-shell-extension-syncthing#70] opened 2022-11-18 21:34 UTC
**Describe the bug**
The Extension cannot be used with Gnome Shell 43.

**Version information:**
 - OS:Manjaro
 - GNOME Shell 43.1
 - gjs 1.74.1
 - "version": 34

**Logs**
```
systemctl --user -n0 status syncthing.service                                                                                                        ✔ 
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
     Loaded: loaded (/usr/lib/systemd/user/syncthing.service; disabled; preset: enabled)
     Active: active (running) since Fri 2022-11-18 22:22:10 CET; 7min ago
       Docs: man:syncthing(1)
   Main PID: 1908 (syncthing)
      Tasks: 22 (limit: 9097)
     Memory: 1.0G
        CPU: 43.293s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/syncthing.service
             ├─1908 /usr/bin/syncthing serve --no-browser --no-restart --logflags=0
             └─1916 /usr/bin/syncthing serve --no-browser --no-restart --logflags=0

                               configRequest@/home/mathias/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:229:26
                                          update@/home/mathias/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:338:18
                                          _callback@/home/mathias/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:413:14
```

Remark: I already adjusted the metadata.json so it shows up as valid. This works halfway - Syncthing is being started, but not shown so in the Icon - it shows the warning sign.

**Comment by jaystrictor** [comment] 2022-12-12 15:43
Duplicate of #69

**Closed by jaystrictor** 2022-12-12 15:43 UTC
