### ISSUE TITLE
TypeError: this.soupSession.queue_message is not a function

### ISSUE THREAD

**Issue by Marthym** [jaystrictor/gnome-shell-extension-syncthing#69] opened 2022-09-21 18:07 UTC
**Describe the bug**
The extension does not work and display warning icon

**Screenshots**

**Version information:**
 - OS: Debian 11.5
 - GNOME Shell 42.4
 - gjs 1.73.1
 - Extension version. 34
   or via the git commit hash.

**Logs**
Add the output of
```
systemctl --user -n0 status syncthing.service
journalctl -b /usr/bin/gnome-shell | grep syncthingicon
```

```
sept. 21 20:03:04 hoth gnome-shell[1604]: JS ERROR: TypeError: this.soupSession.queue_message is not a function
                                          configRequest@/home/user/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:229:26
                                          update@/home/user/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:338:18
                                          _callback@/home/user/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:413:14
```

**Comment by terceiro** [comment] 2022-09-25 15:50
This is caused by newer GNOME versions using soup 3.0 instead of 2.4. In soup 3.0, the Soup `Session` class no longer has a method called `queue_message`

**Comment by nmaggioni** [comment] 2022-11-21 17:30
Soup 3.x seems to follow a bit more convoluted response handling pattern, as seen in [this official GNOME example](https://gitlab.gnome.org/GNOME/gjs/-/blob/f547e2da1a7d06784910aac1f6c25badbefb3193/examples/http-client.js). Message cancellation will probably need to be overhauled too unless I've missed an obvious migration guide - the [standard libsoup 2.x to 3.x migration document](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html) doesn't seem particularly useful for this use case.

**Comment by jaystrictor** [comment] 2022-12-13 20:11
Thanks for the bug report and further investigations. Should be fixed now.

**Closed by jaystrictor** 2022-12-13 20:11 UTC
