### ISSUE TITLE
Feature Request: Icon Change

### ISSUE THREAD

**Issue by svenio** [jaystrictor/gnome-shell-extension-syncthing#20] opened 2016-07-23 14:34 UTC
The "pause" and "arrow" icons indicating activity somewhat break the elegant feel of the extension.  Any chance you'd consider adopting a different approach to showing simple changes in status?

For idle conditions you could use a darker grey icon, or even just a simple static white one like you have now but without the "pause" symbol. 

When the Syncthing is syncing you could use a spinning white icon, or if that's too distracting, then just make the icon a bright white and then have it go grey again when it's done.

Thoughts?

**Comment by jaystrictor** [comment] 2016-07-23 15:58
I am confused. For idle connections we already use the simple static one.
The "pause" icon is not shown when the connection is idle. It is shown when the user stopped Syncthing via the switch in the extension (or via systemd).
If that is not the case for you, please check your logs and consider filing a bug.

#### Regarding spinning icons and colored icons
I don't want to use spinning icons at all. IMHO spinning icons disctract the user from his/her workflow. I very much believe that motionless icons are the way to go and regard motionless icons as one of the main features of this extension.

Also I think that the status indication should not depend solely on the color or brightness of the icon, but I don't have anything against a status indication that combines both (different icon + different color). However, I don't know how this would fit into the usual Gnome symbolic icons.

**Comment by svenio** [comment] 2016-07-23 18:25
You understood perfectly.  I appreciate your comments.

I think, then, I might have just been confused because on my Arch system systemd reports that Syncthing is running, but the extension indicates that it's off.  Refer to my screenshot below...

![screenshot](https://cloud.githubusercontent.com/assets/14263044/17079536/c17c2054-50d8-11e6-8fd0-585c6f859208.png)

**Comment by jaystrictor** [comment] 2016-07-24 11:25
You are running Syncthing as a systemd **system service**.
The extension currently only supports the systemd **user service** (see the README).

To start systemd as a user service, run
```
systemctl --user enable syncthing.service
systemctl --user start syncthing.service
```

If you want to run the service even when the user is logged out, you can enable lingering:
```
sudo loginctl enable-linger username
```


Having said that, probably it would make sense to also support **system services**. I would gladly accept a pull request for that.

**Comment by toddco** [comment] 2016-08-08 18:11
I'm experiencing a similar but different problem.

![screenshot from 2016-08-08 11-49-48crop](https://cloud.githubusercontent.com/assets/20910959/17490663/1f6a5a8e-5d61-11e6-91bb-f237239123c4.png)
Here is the output of my systemctl query. Looks like i do have it loaded as a user service. The problem is the icon only shows the triangle! next to it and no sync folders are shown. Syncthing button is shown as on (running). Attached a screenshot.

System is manjaro gnome3 64bit, Gnome version 3.20.2

~$ systemctl --user status syncthing.service
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
   Loaded: loaded (/usr/lib/systemd/user/syncthing.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-08-08 11:15:22 MDT; 9min ago
     Docs: man:syncthing(1)
 Main PID: 904 (syncthing)
   CGroup: /user.slice/user-1000.slice/user@1000.service/syncthing.service
           └─904 /usr/bin/syncthing -no-browser -no-restart -logflags=0

**Comment by jaystrictor** [comment] 2016-08-08 18:35
@toddco: I would prefer to have a separate GitHub issue for that. Could you open a new issue with your problem? Thank you. Please also include the relevant lines of `journalctl /usr/bin/gnome-shell -e` and check whether there are any errors displayed in the web interface.

**Comment by jaystrictor** [comment] 2016-08-08 19:52
@svenio closing. I think running syncthing as user service is the better approach, as this way the user is able to start and stop the daemon.

**Closed by jaystrictor** 2016-08-08 19:52 UTC
